### ISSUE TITLE
Work with experts to identify lack of realism in the sky images

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#203]
As a long term goal and as we move into data taking, we would like to make produced images after ISR look as realistic as we can.  We should work with experts in camera and survey data to identify important missing or simplified features.  Many issues are already listed and I have a applied a "Realism" label to them.

We can track missing or too simple features here.  Features now tracked via issue include:

- [ ] Add Clouds - #12
- [ ] Sky Glow time structure - #82
- [ ] Vary sky model over sensor - #152
- [ ] Allow the atmospheric transmission curves to vary by airmass - #179
- [ ] Galactic Cirrus  - #135
- [ ] Object opacity - GalSim #550
- [ ] Intra-cluster light -
- [ ] Artifacts - Satellites etc -   
- [ ] Galaxy Morpology with GANs - #134

Experts who have expressed interest in working consulting on this problem include @kadrlica.  Add your name to the issue if you are also interested.

**Comment by kadrlica** [comment]
Here's my hot take: I think that the end game for imSim is as a tool for simulating objects that can be embed into real LSST data. Since the timeline for DC3 may overlap heavily with SV, I think that we should focus on object realism rather that survey or image realism. Based on a semi-arbitrary gauge of what people are worried about in DES, here is my ranked list of priorities. (Note that I am not considering the difficulty of the tasks.)

#### Object Realism
1. Galaxy Morphology
2. Object opacity
3. Intra-cluster light
4. Galactic Cirrus

#### Survey Realism
1. Add Clouds
2. Vary sky model over sensor
3. Sky Glow time structure
4. Artifacts - Satellites etc
