### ISSUE TITLE
Redesign tracking issue

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#238]
Master tracking issue for imSim redesign issues.

(issue still under construction - CWW)

Prerequisites

- [x] #237 - Make imSim run with latest stack  

Issue List:

- [x] #10  - Batoid integration
- [x] #71   - Sky Catalog
- [x] #239 - Use the GalSim config system as a code harness
- [ ] #244 - Re-orient parallelization strategy
- [x] #156 / #243 Refactor and remove LSST sims code.

**Comment by cwwalter** [comment]
Added major issues classes to tracking list.

**Comment by cwwalter** [comment]
Add #244 to tracking list.

**Comment by cwwalter** [comment]
This is all complete except the re-design of the parallelization strategy.  This will now be handled in the context of the GPU pipeline work and will be a post 2.0 release improvement.
