### ISSUE TITLE
List command file options/features that should be configurable or implemented

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#26]
In this issue I am making a list of features that should be configurable (on in some cases implemented) in the command file described in issue #11.  

Options associated with issues:
- [x] - Set exposure time variables (issue #22)
- [x] - Set atmospheric handling (raytraced vs FFT issue #8)
- [x] - Set sky model (ESO vs GalSim default etc issue #5)

Not yet associated with issues:
- [ ] Add the ability to drive different types of inputs with different input files in addition to PhoSim instance files. 
  - [ ] I imagine direct CatSim queries might be possible.  
  - [ ] The ability to drive a setup of CCD sensor level simulations to compare with test stand data for validating the sensor model.  The goal will be to generate a set of data vs simulation reference plots tied to our requirements.  Any implemented model should be able to show adequate agreement (as defined by requirements) between the simulation and test stand data in all of these plots and be callable by the GalSim interface being developed by @rmjarvis.  Specification of what these plots should contain should be make in consultation with the camera team (Note: @smr456) simulators, test stand owners and SAWG.

**Comment by jchiang87** [comment]
How much structure do you think will be needed for these sorts of configuration options?  If we don't need anything beyond key-value pairs, then something like the [`.ini`](https://en.wikipedia.org/wiki/INI_file) would suffice I think.  The `ConfigParser` python module could be used to parse the files so we wouldn't need to add any heavy-weight external dependencies.  If the configs are complicated, we might consider using what the LSST Stack provides do this sort of thing.

**Comment by cwwalter** [comment]
I think simple commands will probably work just fine.  

There is one feature that I have found useful when designing Geant4 (but used like GalSim here) packages like this in the past:  the ability to include other config/.mac files in a file.  This way you can have checked in "blessed" sets of configurations that people can include in their own configurations instead of trying to set things up themselves.  This is a possibility to keep in mind.

**Comment by rmjarvis** [comment]
Some more possible features to consider.

GalSim config files allow the use of a "template" config file from which you can make modifications.  This can be helpful if you have something moderately complicated that you want to serve as your base, and then just modify one or two aspects of it. 

You can also make modifications on the command line, which is convenient for doing scripts where you just want to change file names or directory names or maybe the number of objects to something small while spot testing the script.

**Comment by cwwalter** [comment]
I think we basically have covered most of this old issue.  We either set things in a config file or have commands in the instance catalogs. There is also #71 for which would allow different input types and #74 if we needed special inputs for calibrations.

There are a few things mentioned in the comments like having template config files by @rmjarvis or having the ability include other config files (mentioned by me) that we never addressed.

I am going to close this but feel free to reopen if there is something relevant we don't want to lose or (probably better) make a new stand alone issue.
